### ISSUE TITLE
spi flash write, read, erase routines

### ISSUE THREAD

**Issue by akadamson** [pellepl/stm32_spiffs#1]
Hi, noticed these routines are missing from the sources provided.  While I understand they can be specific to each spi flash type, wondering if it would be possible to see what you used as an example?

**Comment by pellepl** [comment]
Hi, actually it is not very specific to a certain spi flash chip, but rather to the processor and its spi bus peripheral workings. Anyhow, it's all in there - perhaps you forgot to clone the submodules?

Try this:
``` C
git clone --recursive https://github.com/pellepl/stm32_spiffs
```
